---
title: "R Shiny Document"
author: "Anastasia Kunz"
date: "1/26/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tsibble)
library(lubridate)
library(janitor)
library(feasts)
library(shiny)
```

```{r}
truckee <- read_csv("truckee_river.csv", skip = 29) %>% 
  slice(-1) %>% 
  select(datetime, discharge_cfs) %>% 
  mutate(date = mdy(datetime),
         discharge_cfs = as.numeric(discharge_cfs))
```


```{r}
truckee_ts <- truckee %>% 
  as_tsibble(key = NULL, index = date)

#truckee_ts %>% 
 ## gg_season(discharge_cfs)

#ggplot(truckee_ts, aes(x = date, y = discharge_cfs))+
#  geom_line()
```

```{r}
inputPanel(
  dateRangeInput(inputId = "dates", 
                 label = "Select date range:",
                 min = "2010-02-22",
                 max = "2020-02-22",
                 start = "2012-02-02",
                 end = "2014-02-02",
                 format = "yyyy-mm-dd")
)## end input

truckee_react <- reactive({
  
  truckee_ts %>% 
    filter(date >= input$dates[1], # the 1 and 2 is designating the start and end date selected
           date <= input$dates[2])
  
})

renderPlot({
  
  ggplot(data = truckee_react(), aes(x = date, y = discharge_cfs))+
    geom_line()
})

```






